print("Brand_Name Maker")
print("***What is your Brand Name ? Game***")
color=input("What is your favorite color? ")
animal=input("What is your favorite animal? ")
print("Your brands name is "+color+animal)
